version: '3'
services:
  nginx-web:
    build: .
    image: bdcloud/nginx-web
    environment:
     WEB_ADDR: "192.168.31.86:8001, 192.168.31.86:8002, 192.168.31.86:8003"
    restart: unless-stopped
    ports:
     - "8085:8000"
